### ISSUE TITLE
OfbizCommonDocumentationProvider.generateDoc : Cannot invoke method getName() on null object

### ISSUE THREAD

**Issue by Sebbaz** [Nereide-lab/idea-ofbiz-plugin#1]
Hello

I've hot an exception on OFBiz IDEA Integration 1.5.9 : maybe a not nullable var ?

[stacktrace.txt](https://github.com/Nereide-lab/idea-ofbiz-plugin/files/14279885/stacktrace.txt)

```
Java.lang.NullPointerException: Cannot invoke method getName() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:98)
	at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.invokeGroovyObjectInvoker(IndyGuardsFiltersAndSignatures.java:149)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at fr.nereide.documentation.OfbizCommonDocumentationProvider.generateDoc(OfbizCommonDocumentationProvider.groovy:52)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at fr.nereide.documentation.OfbizXmlDocumentationProvider.generateDoc(OfbizXmlDocumentationProvider.groovy:45)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:135)
...
```

**Comment by gtchaboussie** [comment]
Thanks sebastien, i'll look into it !
